# Generated by Django 4.2.7 on 2024-05-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
