# Generated by Django 4.2.7 on 2024-05-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_lesson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
