# Generated by Django 4.2.7 on 2024-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_video_lesson_delete_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
