# Generated by Django 4.2.7 on 2024-05-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_lesson_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
